name: Tests

on:
  pull_request:
    branches: [ stage, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: stage

    steps:
    - name: Set NODE_ENV if prod
      if: github.ref == 'refs/heads/master'
      run: echo ::set-env name=NODE_ENV::prod

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install
      run: npm ci

    - name: Run tests
      run: npm run test
